apiVersion: apps/v1
kind: Deployment
metadata:
  name: njoku-gerald-deployment
  labels:
    app: njoku-gerald
spec:
  replicas: 1
  selector:
    matchLabels:
      app: njoku-gerald
  template:
    metadata:
      labels:
        app: njoku-gerald
    spec:
      containers:
      - name: njoku-gerald
        image: bopgeek/my-express-app:latest 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: njoku-gerald-service
spec:
  selector:
    app: njoku-gerald
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  

  
---
apiVersion: v1
kind: Service
metadata:
  name: njoku-gerald-service
spec:
  selector:
    app: njoku-gerald
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  